name: chatnic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.11
  flutter_svg: ^0.19.1
  http: ^0.13.0
  onboarding: ^3.1.0
  flat_icons_flutter: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
